---
- hosts: k8s
  remote_user: root
  vars:
    http_port: 8088
  
  tasks:
    - name: yum install net-tools
      yum:
        name: net-tools
        state: present
    - name: stop firewalld service
      service:
        name: "{{ item }}"
        state: started
      loop:
        - firewalld
    - name: mkdir scripts
      file:
        path: "/opt/scripts"
        state: directory
        owner: root
        group: root
    - name: copy auto_scripts
      copy: 
        src: '{{ item.src }}' 
        dest: /opt/scripts/
        mode: 0755
      with_items:
        - { src: '/root/auto_add_gpt_disk.sh'}
        - { src: '/root/auto_install_docker.sh'}
    - name: run add_disk_sh
      command: /bin/bash /opt/scripts/auto_add_gpt_disk.sh
    - name: run add_docker_sh
      command: /bin/bash /opt/scripts/auto_install_docker.sh